### ISSUE TITLE
Fix Seaport private/reserved sale double-counting bug

### ISSUE THREAD

**Issue by dsgriffin** [dsgriffin/nft-sales-twitter-bot#18]
Private/reserved sales via. Seaport seem to have duplicate event logs, causing price calculations to be double the value they should be.

**Comment by bhishp** [comment]
I have added the following code to fix this on our fork: https://github.com/gmdaoeth/nft-sales-twitter-bot/pull/12

Though, I am not familiar with the Seaport contract, maybe you can comment if this is a fix as you might expect?

**Comment by dsgriffin** [comment]
@bhishp hi, sorry for the delayed reply - does this handle tx's where it splits the payments in two event logs? seems to be quite a common thing. i'm wondering if you've noticed that adding that in fixes the bug but also misses some sales?
