### ISSUE TITLE
New Opensea Seaport Contract

### ISSUE THREAD

**Issue by Cilooth** [dsgriffin/nft-sales-twitter-bot#5]
Opensea recently released their new marketplace smart contract, Seaport 1.1
This completely broke the tracking of Opensea sales.

Documentation: https://docs.opensea.io/v2.0/reference/seaport-overview

I'm trying to fix this on my end to submit a PR but it seems that they used a whole new structure and didn't include a "price" log in the new OrderFulfilled Event. Getting the full paid price might force us to run calculations not needed for other marketplaces such as Looksrare. 

Feel free to comment on this issue if you are also working on a fix

**Comment by dsgriffin** [comment]
frustrating. sadly I can't allocate time right now for a fix, but any PR's from people using this script are welcome

**Comment by Baggns** [comment]
Yeah run into the same issue. Did not yet found a easy workaround. If I every find one I will share it here...

**Comment by Pukson** [comment]
Same issue yeah. This weekend im gonna wrap my head around it and see how to fix it

**Comment by kenryu42** [comment]
This should decode the OrderFulfilled event.
You need to **exclude** indexed parameters offerer & zone.
```
logDecoder: [{
      type: 'bytes32',
      name: 'orderHash'
    },
    {
      type: 'address',
      name: 'recipient'
    },
    {
      type: 'tuple[]',
      name: 'offer',
      components: [{
          type: 'uint8',
          name: 'itemType'
        },
        {
          type: 'address',
          name: 'token'
        },
        {
          type: 'uint256',
          name: 'identifier'
        },
        {
          type: 'uint256',
          name: 'amount'
        }
      ]
    },
    {
      type: 'tuple[]',
      name: 'consideration',
      components: [{
          type: 'uint8',
          name: 'itemType'
        },
        {
          type: 'address',
          name: 'token'
        },
        {
          type: 'uint256',
          name: 'identifier'
        },
        {
          type: 'uint256',
          name: 'amount'
        },
        {
          type: 'address',
          name: 'recipient'
        }
      ]
    }

web3.eth.abi.decodeLog(
  logDecoder,
  log.data,
  []
);
```
If it doesn't work on your end, try my repository.
https://github.com/kenryu42/ethereum-nft-sales-bot

**Comment by dsgriffin** [comment]
@kenryu42 thanks will check when i get a bit of time. will include you in the credits section if we incorporate anything from your repo

**Comment by dsgriffin** [comment]
hi all, took a quick look this morning and pushed some changes up (thanks @kenryu42 - added you to the credits section). 

the bot should now work for seaport, wyvern, looksrare & x2y2.
