### ISSUE TITLE
[Feature Request] Watch Multiple collections parallelly

### ISSUE THREAD

**Issue by Deveshb15** [dsgriffin/nft-sales-twitter-bot#9]
### What I was thinking is if it's possible to watch and tweet on multiple collections simultaneously?

In the app.js on the last line when the function is called instead of just calling the function without args what if we did this?
```js
    monitorContract(process.env.CONTRACT_ADDRESS1, abi1);
    monitorContract(process.env.CONTRACT_ADDRESS2, abi2);
```

will have to make same changes for functions in utils too just need to add CONTRACT_ADDRESS as arguments.

Have tried this and worked fine for me with collections that were currently minting, didn't get rate-limited which is the only thing that I was worried about

**would love to open a pull request if this makes sense or am I missing something?**

**Comment by dsgriffin** [comment]
It's certainly possible! but a feature better suited for a fork than as part of this repo, that I'd rather keep simple

**Comment by bhishp** [comment]
> ### What I was thinking is if it's possible to watch and tweet on multiple collections simultaneously?
> In the app.js on the last line when the function is called instead of just calling the function without args what if we did this?
> 
> ```js
>     monitorContract(process.env.CONTRACT_ADDRESS1, abi1);
>     monitorContract(process.env.CONTRACT_ADDRESS2, abi2);
> ```
> 
> will have to make same changes for functions in utils too just need to add CONTRACT_ADDRESS as arguments.
> 
> Have tried this and worked fine for me with collections that were currently minting, didn't get rate-limited which is the only thing that I was worried about
> 
> **would love to open a pull request if this makes sense or am I missing something?**

We do this on our fork, you simply pass a comma-seperated list for CONTRACT_ADDRESSES and it will monitor them all. https://github.com/gmdaoeth/nft-sales-twitter-bot/blob/master/app.js#L25

```
CONTRACT_ADDRESSES=0x0E42FfbaC75Bcc30Cd0015F8aAA608539ba35FbB,0x65d8b2BF930a0015028eFCaEE5AF7bf61b90b76f,0x1E725bcc09aD221D35af5aDEdA404Fb2147b43fa
```
